on:
  push:
    branches:
      - main
name: ğŸš€ Deploy website on

jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: unbuntu-lastest
    steps:
      - name: ğŸšš Get lastest code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: ğŸ”¨ Build FrontEnd
        run: |
          cd client
          npm install
          npm run build

      - name: ğŸ”¨ Build BackEnd
        run: |
          cd server
          npm install
          npm run start

      - name: ğŸ“ Sync File
      uses: AkekoChan/flami-app
      with:
      server:
