on:
  push:
    branches:
      - main
name: ğŸš€ Deploy website on

jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get lastest code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: ğŸ”¨ Build FrontEnd
        run: |
          cd client
          npm install
          npm run build

      - name: ğŸ“ Sync File
      uses: AkekoChan/flami-app
      with:
        server: ${{ secrets.GIT_CPANEL_SERVER }}
        username: ${{ secrets.GIT_CPANEL_USER }}
        password: ${{ secrets.GIT_CPANEL_PWD }}
        protocol: ${{ secrets.GIT_CPANEL_PROTOCOL }}
        local-dir: ./build/
